name: PullRequest

on: [ pull_request ]

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Run tests
        run: ./gradlew test
        env:
          VERSION: ${{ github.ref }}
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        env:
          VERSION: ${{ github.ref }}
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: IOIO-Espresso-report
          path: applications/**/build/reports/androidTests/connected/
      - name: Save logcat output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: IOIO-logcat
          path: artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: IOIO-Screenshots
          path:  |
            applications/**/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            applications/**/build/outputs/androidTest-results/connected
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: IOIO-Lint-report
          path: applications/**/build/reports/lint-results.html
